name: DBsBlockBreaker
version: '1.0'
main: net.dbsgameplay.blockbreaker.DBsGameplayBlockBreaker
api-version: '1.20'

commands:
  pickaxe:
    permissiom: blockbreaker.get
  sellall:
  bupgrade:
  bhelp:
  mine:
