name: DbsGameplayCore
version: '1.0'
main: net.dbsgameplay.core.DBsGameplayCore
api-version: '1.20'
author: DBsGameplay Development Team

loadbefore:
  - DbsGameplayBlockBreaker
  - DbsGameplayDungeonCrusher
  - DbsGameplayAdminTool
  - DbsGameplaySkyBlock

commands:
  fly:
    aliases: [fliegen, flug]
    permission: dbsgameplay.core.team.fly
    description: Fliege wie ein Vogel!